### ISSUE TITLE
bitcoin module

### ISSUE THREAD

**Issue by selivandex** [secnot/bitcoin-balance#1]
Hey. What is bitcoin module do u use?

I getting this error

```Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from bitbalance import BitcoinBalanceFacade, Session, bitcoin_to_string
  File "/home/selivanov/bitcoin-balance/bitbalance/__init__.py", line 1, in <module>
    from .core import BitcoinBalanceFacade
  File "/home/selivanov/bitcoin-balance/bitbalance/core.py", line 11, in <module>
    import bitcoin.rpc```

**Comment by selivandex** [comment]
Found https://github.com/petertodd/python-bitcoinlib

**Comment by secnot** [comment]
Hi

The app is still under development this python version was a prototype for the golang app that will probably be released next month. I would only use as an example for python-bitcoinlib for now.

**Comment by selivandex** [comment]
So it doesn't work, right? i'm about python version

Because i getting error always
```
[2017-08-22 08:20:54,920] [ERROR] [           core.py:325 -  _poll_thread_func() ] [Unexpected exception:]
Traceback (most recent call last):
  File "/home/selivanov/bitcoin-balance/bitbalance/core.py", line 319, in _poll_thread_func
    block = self._block_factory.build_block(cblock, height)
  File "/home/selivanov/bitcoin-balance/bitbalance/primitives.py", line 293, in build_block
    outputs = self._block_outputs(block)
  File "/home/selivanov/bitcoin-balance/bitbalance/primitives.py", line 275, in _block_outputs
    block_txouts.extend(self._transaction_outputs(tx))
  File "/home/selivanov/bitcoin-balance/bitbalance/primitives.py", line 259, in _transaction_outputs
    txhash = tx.GetTxid()
AttributeError: 'CTransaction' object has no attribute 'GetTxid'
```

**Comment by secnot** [comment]
If I remember correctly the current release of python-bitcoinlib doesn't support segwit, so that code  uses  GetTxid() from a pull request that does. Installing it should fix the error.

Either way this repo is not working yet, I have a python version planned but first I will finish the golang one.

**Comment by selivandex** [comment]
Why didn't you use just libbitcoin-explorer ?

**Comment by secnot** [comment]
I'm developing a bitcoin payment service, for that I need to to be able to obtain the balance for any address, a very common problem but unfortunately bitcoind doesn't have that functionality, I could use a 3rd party full node that does, like btcd or libbitcoin-server. 

Or I could program as custom bitcoind client that provides JUST the functionality I need, with a much lower memory and storage footprint so it can be deployed on inexpensive vps, that connect to a central full node.

I choose the second option, first developed a python prototype with python-bitcoinlib but  ended switching to golang with btcrpclient.

Libbitcoin was a possibility but, the storage/ram requirements are too high.

**Comment by selivandex** [comment]
Ok. Nice

Do you ever used or saw this lib? https://github.com/piotrnar/gocoin

https://bitcoin.stackexchange.com/questions/10895/calculating-address-balance

**Comment by secnot** [comment]
It requires licensing for commercial use and alot of ram. 

Apart from the initial sync where as much memory as possible is needed to minimize disk access, I don't see why so much memory is required. A new block can be processed with all the utxo stored in a ssd in a few hundred milliseconds, less than a 1GB of ram should be more than enough to cache the most recent blocks in a synced node.
